#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Aura_android.Resource", IsApplication=true)]

namespace Aura_android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060014
			public const int Narrate_next = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int Narrate_previous = 2131099666;
			
			// aapt resource value: 0x7f060008
			public const int btnRecord = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int btn_createuser = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int btn_next = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int btn_testLights = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int conn_hue = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int displayHue = 2131099649;
			
			// aapt resource value: 0x7f060016
			public const int editEmail = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int editPassword = 2131099671;
			
			// aapt resource value: 0x7f06001b
			public const int genreList = 2131099675;
			
			// aapt resource value: 0x7f060000
			public const int instructions = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout1 = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout2 = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout3 = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int linearLayout4 = 2131099665;
			
			// aapt resource value: 0x7f06001c
			public const int listview_stories = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int loginTitle = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int record_start = 2131099667;
			
			// aapt resource value: 0x7f060018
			public const int signin_button = 2131099672;
			
			// aapt resource value: 0x7f06000e
			public const int speech_box = 2131099662;
			
			// aapt resource value: 0x7f06001a
			public const int spinner1 = 2131099674;
			
			// aapt resource value: 0x7f060010
			public const int story_box = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int textView1 = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int textView3 = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int textView4 = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int textYourText = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int text_pressBtn = 2131099651;
			
			// aapt resource value: 0x7f060019
			public const int welcome_content = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int welcome_next = 2131099677;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HueConnect = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HueCreateUser = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Narrate = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SignIn = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int StoryPick = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Welcome = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int bird_cut = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int flame_cut = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int flute_cut = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int rain_cut = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int rooster_cut = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int thunder_cut = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int wind_cut = 2130968582;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int messageSpeakNow = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
